/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import static View.MainFrame.tblStudentList;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JayJomJohn
 */
public class AddNewStudent extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    String imagePath = null;
    
    public AddNewStudent() {
        initComponents();
        conn=JavaConnector.ConnectDb();
        showJframeSize();
        showIcon();
        Disable();
    }

    private void showIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/school.png")));
    }
    
    private void showJframeSize(){
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        label_photo = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        radio_male = new javax.swing.JRadioButton();
        radio_female = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_birthdate = new com.toedter.calendar.JDateChooser();
        txt_middlename = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        btnBrowse = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txt_contact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD NEW STUDENT");
        setMaximumSize(new java.awt.Dimension(1240, 450));
        setMinimumSize(new java.awt.Dimension(1240, 450));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 450));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Date of Birth:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 110, 30));

        txt_lastname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_lastnameKeyReleased(evt);
            }
        });
        jPanel1.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 250, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("FirstName:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 90, 30));

        txt_firstname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_firstnameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Age:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, 50, 30));

        txt_age.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ageKeyTyped(evt);
            }
        });
        jPanel1.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 50, 30));

        label_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        jPanel1.add(label_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 180, 170));

        btnClose.setBackground(new java.awt.Color(153, 0, 51));
        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_delete_sign_35px.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setBorderPainted(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 180, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("LastName:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 30));

        buttonGroup1.add(radio_male);
        radio_male.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radio_male.setText("Male");
        radio_male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_male.setFocusPainted(false);
        jPanel1.add(radio_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 90, 30));

        buttonGroup1.add(radio_female);
        radio_female.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radio_female.setText("Female");
        radio_female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_female.setFocusPainted(false);
        jPanel1.add(radio_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 110, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Address:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("MiddleName:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 110, 30));

        txt_birthdate.setDateFormatString("yyyy-MM-d");
        txt_birthdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 260, 30));

        txt_middlename.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_middlename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_middlenameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, 50, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Gender:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 30));

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 800, -1));

        btnBrowse.setBackground(new java.awt.Color(102, 0, 102));
        btnBrowse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBrowse.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_image_file_35px.png"))); // NOI18N
        btnBrowse.setText("BROWSE");
        btnBrowse.setBorderPainted(false);
        btnBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrowse.setFocusPainted(false);
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        jPanel1.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 230, 180, -1));

        btnAdd.setBackground(new java.awt.Color(0, 51, 102));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_add_user_35px_2.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 180, 40));

        txt_contact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contactKeyPressed(evt);
            }
        });
        jPanel1.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 250, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Contact:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 30));

        btnNew.setBackground(new java.awt.Color(204, 102, 0));
        btnNew.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_edit_user_35px.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.setBorderPainted(false);
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew.setFocusPainted(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txt_contactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactKeyPressed
        String phonenum = txt_contact.getText();
        int length = phonenum.length();
        char c = evt.getKeyChar();        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9') {
            if(length<11) {            
            txt_contact.setEditable(true);            
            }else{
            txt_contact.setEditable(false);
            getToolkit().beep();
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE) {
                txt_contact.setEditable(true);                
            }else{
                txt_contact.setEditable(false);
                getToolkit().beep();
            }
            
        }
    }//GEN-LAST:event_txt_contactKeyPressed

    private void txt_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyTyped
        if(txt_age.getText().length()>2){
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_ageKeyTyped

    private void txt_middlenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_middlenameKeyTyped
        if(txt_middlename.getText().length() >= 1){
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_middlenameKeyTyped

    private void txt_lastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastnameKeyReleased
        if (!txt_lastname.getText().equals("")) {
            btnClose.setText("CANCEL");
        } else {
            btnClose.setText("BACK");
        }
    }//GEN-LAST:event_txt_lastnameKeyReleased

    private void txt_firstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstnameKeyTyped
         if (txt_firstname.getText().length() >= 16) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_firstnameKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       txt_birthdate.getCalendarButton().setText("Choose Date");
       
    }//GEN-LAST:event_formWindowOpened
        //IMAGERESIZE
    public ImageIcon resizePic (String picPath){
        ImageIcon myImg = new ImageIcon(picPath);
        Image img = myImg.getImage().getScaledInstance(label_photo.getWidth(), label_photo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon myPic = new ImageIcon(img);
        return myPic;
    }
    
    private void browse(){
         JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        //File Extension
        FileNameExtensionFilter fFilter = new FileNameExtensionFilter("*.Images","jpg","png","gif");
        fc.addChoosableFileFilter(fFilter);
        
        int fileState = fc.showSaveDialog(null);
        
        //if user select a file
        if (fileState == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fc.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            imagePath = path;
            
            //display the image in jLabel
            label_photo.setIcon(resizePic(path));
        }
        // if the user cancel
        else if (fileState == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No image selected");
        }
    }
    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
      browse();
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        if(txt_firstname.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"FirstName cannot be empty","Warning!",JOptionPane.ERROR_MESSAGE);
            txt_firstname.requestFocus();
        
        }else if(txt_lastname.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"LastName cannot be empty","Warning!",JOptionPane.ERROR_MESSAGE);
            txt_lastname.requestFocus();
        
        }else if(txt_middlename.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"MiddleName cannot be empty","Warning!",JOptionPane.ERROR_MESSAGE);
            txt_middlename.requestFocus();
        
        }else if(radio_male.isSelected() == false && radio_female.isSelected() == false){
            getToolkit().beep();
           JOptionPane.showMessageDialog(null, "You must select a valid type to proceed!", "WARNING!", JOptionPane.ERROR_MESSAGE);      
        
        }else if(((JTextField)txt_birthdate.getDateEditor().getUiComponent()).getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Birthdate cannot be empty","Warning!",JOptionPane.ERROR_MESSAGE);
            txt_birthdate.requestFocus();
        
        }else if(txt_age.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Age cannot be empty","Warning!",JOptionPane.ERROR_MESSAGE);
            txt_age.requestFocus();
        
        }else if(txt_address.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Address cannot be empty","Warning!",JOptionPane.ERROR_MESSAGE);
            txt_address.requestFocus();
        
        }else if(txt_contact.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Contact cannot be empty","Warning!",JOptionPane.ERROR_MESSAGE);
            txt_birthdate.requestFocus();
        
        }else if(imagePath != null){
            
            try {
                String sql = "INSERT INTO `students`(`LastName`, `FirstName`, `MiddleName`, `Gender`, `Birthdate`, `Age`, `Contact`, `Address`, `Picture`,`Status`) "
                        + "VALUES (?,?,?,?,?,?,?,?,?,'Active')";
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_lastname.getText().toUpperCase());
                pst.setString(2,txt_firstname.getText().toUpperCase());
                pst.setString(3,txt_middlename.getText().toUpperCase());
                radio_male.setActionCommand("Male");
                radio_female.setActionCommand("Female");
                pst.setString(4,buttonGroup1.getSelection().getActionCommand());
                pst.setString(5, ((JTextField)txt_birthdate.getDateEditor().getUiComponent()).getText());
                pst.setString(6,txt_age.getText());
                pst.setString(7,txt_contact.getText().toUpperCase());
                pst.setString(8,txt_address.getText().toUpperCase());
                InputStream img = new FileInputStream(imagePath);
                pst.setBlob(9,img);
                if (pst.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(this, "Successfully Added!", "ATTENTION", JOptionPane.INFORMATION_MESSAGE);
                    clear();
                    showStudents();
                    Disable();
                    btnClose.setEnabled(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,e);
            }
        
        
        //IMAGEVALIDATION
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "No Photo Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            browse();
        }
        
    }//GEN-LAST:event_btnAddActionPerformed
    //DISABLE
    private void Disable(){
        txt_lastname.setEnabled(false);
        txt_firstname.setEnabled(false);
        txt_middlename.setEnabled(false);
        radio_male.setEnabled(false);
        radio_female.setEnabled(false);
        txt_birthdate.setEnabled(false);
        txt_age.setEnabled(false);
        txt_address.setEnabled(false);
        txt_contact.setEnabled(false);
        btnAdd.setEnabled(false); 
        btnBrowse.setEnabled(false);
        btnClose.setEnabled(false);
        btnNew.setEnabled(true);
    }
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txt_lastname.setEnabled(true);
        txt_firstname.setEnabled(true);
        txt_middlename.setEnabled(true);
        radio_male.setEnabled(true);
        radio_female.setEnabled(true);
        txt_birthdate.setEnabled(true);
        txt_age.setEnabled(true);
        txt_address.setEnabled(true);
        txt_contact.setEnabled(true);
        btnBrowse.setEnabled(true);
        btnClose.setEnabled(true);
        btnAdd.setEnabled(true);
        btnNew.setEnabled(false);
    }//GEN-LAST:event_btnNewActionPerformed
    //CLEAR
    private void clear(){
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_middlename.setText("");
        buttonGroup1.clearSelection();
        ((JTextField)txt_birthdate.getDateEditor().getUiComponent()).setText("");
        txt_age.setText("");
        txt_address.setText("");
        label_photo.setIcon(null);
    }
    
    private void showTableResize(){
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);       
        for (int i = 1; i < 11; i++) {
            
            tblStudentList.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);           
            tblStudentList.getColumnModel().getColumn(i).setPreferredWidth(150);
            
        }

    }
    private void showStudents(){
        try {
            String sql = "SELECT * FROM Students ORDER BY id ASC";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            MainFrame.tblStudentList.setModel(DbUtils.resultSetToTableModel(rs));
            MainFrame.tblStudentList.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            showTableResize();
        } catch (Exception e) {
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
               UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNew;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_photo;
    public javax.swing.JRadioButton radio_female;
    public javax.swing.JRadioButton radio_male;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_age;
    private com.toedter.calendar.JDateChooser txt_birthdate;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_middlename;
    // End of variables declaration//GEN-END:variables
}
