/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author Joshua C. Magoliman
 */
public class CreateAnotherAccount extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    public CreateAnotherAccount() {
        initComponents();
        conn=JavaConnector.ConnectDb();
        showIcon();
        Reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        chckbox_ShowPassword = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        lblSecretAnswer = new javax.swing.JLabel();
        cmbboxSecretQuestion = new javax.swing.JComboBox<>();
        lblSecretQuestion = new javax.swing.JLabel();
        txtSecretAnswer = new javax.swing.JPasswordField();
        chckbox_ShowSecretAnswer = new javax.swing.JCheckBox();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CREATE ANOTHER ACCOUNT ?");
        setMinimumSize(new java.awt.Dimension(526, 390));
        setResizable(false);

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(153, 0, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 135, 40));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsername.setName(""); // NOI18N
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });
        jPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 203, -1));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername.setText("USERNAME");
        jPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 50, 100, 30));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setText("PASSWORD");
        jPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, 30));

        chckbox_ShowPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        chckbox_ShowPassword.setText("Show Password");
        chckbox_ShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chckbox_ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbox_ShowPasswordActionPerformed(evt);
            }
        });
        jPanel.add(chckbox_ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 203, -1));

        lblSecretAnswer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSecretAnswer.setText("SECRET ANSWER");
        jPanel.add(lblSecretAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 150, 30));

        cmbboxSecretQuestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbboxSecretQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "What is your favorite color?", "What is your contact number?", "When is your birthday?", "What is love for you?", "Where were you born ?", "What is the meaning of life?", "What is your gender?", "What is your civil status in life?", "What is your dream in life?", "What things that makes you happy?", "What things that makes you sad?", "What things that makes you mad?", "What is your job?", "What is your favorite song?", "What is your favorite band?", "What is your favorite singer?" }));
        cmbboxSecretQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel.add(cmbboxSecretQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 250, -1));

        lblSecretQuestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSecretQuestion.setText("SECRET QUESTION");
        jPanel.add(lblSecretQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 30));

        txtSecretAnswer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSecretAnswer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSecretAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSecretAnswerKeyTyped(evt);
            }
        });
        jPanel.add(txtSecretAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 250, 30));

        chckbox_ShowSecretAnswer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        chckbox_ShowSecretAnswer.setText("Show Secret Answer");
        chckbox_ShowSecretAnswer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chckbox_ShowSecretAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbox_ShowSecretAnswerActionPerformed(evt);
            }
        });
        jPanel.add(chckbox_ShowSecretAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        btnRegister.setBackground(new java.awt.Color(0, 51, 153));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.setBorderPainted(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setFocusPainted(false);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 126, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 private void Reset() {
        txtUsername.setText("");
        txtPassword.setText("");
        cmbboxSecretQuestion.setSelectedItem("None");
        txtSecretAnswer.setText("");
        chckbox_ShowPassword.setSelected(false);
        chckbox_ShowSecretAnswer.setSelected(false);
        this.txtUsername.requestFocus();
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (btnBack.getText().equals("BACK")) {
            this.hide();
            new LoginForm().setVisible(true);
        } else {
            int P = JOptionPane.showConfirmDialog(null, " Are you sure want to cancel ?", "ATTENTION", JOptionPane.YES_NO_OPTION);
            if (P == JOptionPane.YES_OPTION) {
                this.hide();
                new LoginForm().setVisible(true);
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed
    private void chckbox_ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbox_ShowPasswordActionPerformed
        if (chckbox_ShowPassword.isSelected()) {
            txtPassword.setEchoChar((char) 0);
        } else {
            txtPassword.setEchoChar('*');
        }
        this.lblUsername.requestFocus();
    }//GEN-LAST:event_chckbox_ShowPasswordActionPerformed
    private void chckbox_ShowSecretAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbox_ShowSecretAnswerActionPerformed
        if (chckbox_ShowSecretAnswer.isSelected()) {
            txtSecretAnswer.setEchoChar((char) 0);
        } else {
            txtSecretAnswer.setEchoChar('*');
        }
        this.lblUsername.requestFocus();
    }//GEN-LAST:event_chckbox_ShowSecretAnswerActionPerformed
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Username Found !", "ATTENTIOM", JOptionPane.ERROR_MESSAGE);
            txtUsername.requestFocus();
        } else if (txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Password Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtPassword.requestFocus();
        } else if (cmbboxSecretQuestion.getSelectedItem().equals("None")) {
            JOptionPane.showMessageDialog(this, "No Secret Question Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            cmbboxSecretQuestion.requestFocus();
        } else if (txtSecretAnswer.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Secret Answer Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtSecretAnswer.requestFocus();
        } else {
            try {
                pst = conn.prepareStatement("SELECT * FROM Users WHERE Username=?");
                pst.setString(1, txtUsername.getText());
                rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "This Username is already taken!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
                } else {
                    CreatingAccount();
                }
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed
    private void CreatingAccount() {
        try {
            String sql = "INSERT INTO users(username,password,secret_question,secret_answer)VALUES(?,?,?,?)";
            pst = conn.prepareCall(sql);
            pst.setString(1, txtUsername.getText());
            pst.setString(2, txtPassword.getText());
            pst.setString(3, cmbboxSecretQuestion.getSelectedItem().toString());
            pst.setString(4, txtSecretAnswer.getText());
            if (pst.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(this, "SUCCESSFULLY REGISTERED");
                Reset();
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtUsername.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUsernameKeyTyped
    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        if (!txtUsername.getText().equals("")) {
            btnBack.setText("CANCEL");
        } else {
            btnBack.setText("BACK");
        }
    }//GEN-LAST:event_txtUsernameKeyReleased
    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtPassword.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPasswordKeyTyped
    private void txtSecretAnswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSecretAnswerKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || Character.isWhitespace(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtSecretAnswer.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSecretAnswerKeyTyped
    //DISPLAY ICON
    private void showIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/school.png")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAnotherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAnotherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAnotherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAnotherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAnotherAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox chckbox_ShowPassword;
    private javax.swing.JCheckBox chckbox_ShowSecretAnswer;
    private javax.swing.JComboBox<String> cmbboxSecretQuestion;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSecretAnswer;
    private javax.swing.JLabel lblSecretQuestion;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtSecretAnswer;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
