/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author JayJomJohn
 */
public class ForgotPassword extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    public ForgotPassword() {
        initComponents();
        conn=JavaConnector.ConnectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        cmbboxSecretQuestion = new javax.swing.JComboBox<>();
        txtSecretAnswer = new javax.swing.JPasswordField();
        lblUsername1 = new javax.swing.JLabel();
        lblUsername2 = new javax.swing.JLabel();
        chckboxSecretAnswer = new javax.swing.JCheckBox();
        btnShowPassword = new javax.swing.JButton();
        txtShowPassword = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(515, 400));
        setPreferredSize(new java.awt.Dimension(515, 400));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername.setText("Secret Answer:");
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 30));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsername.setName(""); // NOI18N
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 260, -1));

        cmbboxSecretQuestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbboxSecretQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "What is your favorite color?", "What is your contact number?", "When is your birthday?", "What is love for you?", "Where were you born ?", "What is the meaning of life?", "What is your gender?", "What is your civil status in life?", "What is your dream in life?", "What things that makes you happy?", "What things that makes you sad?", "What things that makes you mad?", "What is your job?", "What is your favorite song?", "What is your favorite band?", "What is your favorite singer?" }));
        jPanel1.add(cmbboxSecretQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 260, 30));

        txtSecretAnswer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSecretAnswer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSecretAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSecretAnswerKeyTyped(evt);
            }
        });
        jPanel1.add(txtSecretAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 260, -1));

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername1.setText("USERNAME");
        jPanel1.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 40, 160, 30));

        lblUsername2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername2.setText("Secret Question:");
        jPanel1.add(lblUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 80, 160, 30));

        chckboxSecretAnswer.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        chckboxSecretAnswer.setText("Show Secret Answer");
        chckboxSecretAnswer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chckboxSecretAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckboxSecretAnswerActionPerformed(evt);
            }
        });
        jPanel1.add(chckboxSecretAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        btnShowPassword.setBackground(new java.awt.Color(204, 204, 0));
        btnShowPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnShowPassword.setText("SHOW PASSWORD");
        btnShowPassword.setBorderPainted(false);
        btnShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowPassword.setFocusPainted(false);
        btnShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 140, 30));

        txtShowPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtShowPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtShowPassword.setName(""); // NOI18N
        jPanel1.add(txtShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 260, 30));

        btnBack.setBackground(new java.awt.Color(153, 0, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 270, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        try {
            pst = conn.prepareStatement("SELECT Secret_Question FROM Users WHERE Username=?");
            pst.setString(1, txtUsername.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                String getter = rs.getString("Secret_Question");
                cmbboxSecretQuestion.setSelectedItem(getter);
            } else {
                cmbboxSecretQuestion.setSelectedItem("None");
                txtShowPassword.setText("");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtUsername.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void txtSecretAnswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSecretAnswerKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || Character.isWhitespace(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtSecretAnswer.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSecretAnswerKeyTyped

    private void chckboxSecretAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckboxSecretAnswerActionPerformed
        if (chckboxSecretAnswer.isSelected()) {
            txtSecretAnswer.setEchoChar((char) 0);
        } else {
            txtSecretAnswer.setEchoChar('*');
        }
        this.lblUsername.requestFocus();
    }//GEN-LAST:event_chckboxSecretAnswerActionPerformed

    private void btnShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPasswordActionPerformed
        if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Username Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtUsername.requestFocus();
        } else if (cmbboxSecretQuestion.getSelectedItem().equals("None")) {
            JOptionPane.showMessageDialog(this, "No Secret Question Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            cmbboxSecretQuestion.requestFocus();
        } else if (txtSecretAnswer.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Secret Answer Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtSecretAnswer.requestFocus();
        } else {
            try {
                pst = conn.prepareStatement("SELECT Password FROM Users WHERE Username = ? AND BINARY Secret_Question = ? AND BINARY Secret_Answer = ?");
                pst.setString(1, txtUsername.getText());
                pst.setString(2, (String) cmbboxSecretQuestion.getSelectedItem());
                pst.setString(3, txtSecretAnswer.getText());
                rs = pst.executeQuery();
                if (rs.next()) {
                    String getter = rs.getString("Password");
                    txtShowPassword.setText(getter);
                    txtShowPassword.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Details!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
                    txtShowPassword.setEnabled(false);
                    txtShowPassword.setText("");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnShowPasswordActionPerformed
     private void Reset() {
        txtUsername.setText("");
        txtShowPassword.setText("");
        cmbboxSecretQuestion.setSelectedIndex(0);
        txtShowPassword.setEnabled(false);
        this.txtUsername.requestFocus();
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.hide();
        Reset();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnShowPassword;
    private javax.swing.JCheckBox chckboxSecretAnswer;
    private javax.swing.JComboBox<String> cmbboxSecretQuestion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JPasswordField txtSecretAnswer;
    private javax.swing.JTextField txtShowPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
