/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JayJomJohn
 */
public class MainFrame extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    public MainFrame() {
        initComponents();
        conn=JavaConnector.ConnectDb();
        showIcon();
        showStudents();
    }
    
    private void showIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/school.png")));
    }
    private void showTableResize(){
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);       
        for (int i = 1; i < 11; i++) {
            
            tblStudentList.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);           
            tblStudentList.getColumnModel().getColumn(i).setPreferredWidth(150);
            
        }

    }
    
     private void showStudents(){
        try {
            String sql = "SELECT * FROM Students ORDER BY id ASC";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblStudentList.setModel(DbUtils.resultSetToTableModel(rs));
            tblStudentList.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            this.label_entry.setText("TOTAL ENTRY: " + tblStudentList.getRowCount());
            showTableResize();     
        } catch (Exception e) {
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_user = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label_entry = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        cmb_filter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudentList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAINFRAME");
        setMinimumSize(new java.awt.Dimension(1300, 650));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_user_male_circle_35px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 40, 50));

        label_user.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_user.setForeground(new java.awt.Color(255, 255, 255));
        label_user.setText("label User");
        jPanel2.add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 140, 30));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_shutdown_25px.png"))); // NOI18N
        jButton3.setText("LogOut");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 50));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_delete_35px.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, 180, 40));

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_add_user_35px_2.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, 180, 40));

        label_entry.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_entry.setText("TOTAL ENTRY:");
        jPanel1.add(label_entry, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 240, 40));

        txt_search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 260, 40));

        cmb_filter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "ID", "LastName", "FirstName", "MiddleName" }));
        cmb_filter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cmb_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 240, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_search_35px_2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 50, 40));

        tblStudentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStudentList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblStudentList.setFillsViewportHeight(true);
        tblStudentList.getTableHeader().setReorderingAllowed(false);
        tblStudentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentListMouseClicked(evt);
            }
        });
        tblStudentList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblStudentListKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblStudentList);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 130, 1240, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new AddNewStudent().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel d = (DefaultTableModel)tblStudentList.getModel();
        int row = tblStudentList.getSelectedRow();
        int id = Integer.parseInt(d.getValueAt(row, 0).toString());
        
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want to Delete the Record","Warning!",JOptionPane.YES_NO_OPTION);
        if(YesOrNo == JOptionPane.YES_OPTION){
             try {
                String sql = "DELETE FROM `students` WHERE id=?";
                pst=conn.prepareStatement(sql);
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Successfully Deleted Brand","Deleted",JOptionPane.PLAIN_MESSAGE);
                showStudents();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblStudentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentListMouseClicked

        
        StudentProfile sp = new StudentProfile();
        try {
            int row = tblStudentList.getSelectedRow();
            String Table_click=(tblStudentList.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM students WHERE id='"+Table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();            
            if(rs.next()) {
               sp.txt_id.setText(rs.getString("id"));
               sp.txt_firstname.setText(rs.getString("firstname"));
               sp.txt_middlename.setText(rs.getString("middlename"));
               sp.txt_lastname.setText(rs.getString("lastname"));
               String g = rs.getString("gender");
               if("Male".equals(g)){
                   sp.radio_male.setSelected(true);
                   sp.radio_male.setForeground(Color.GREEN);
                   tblStudentList.setSelectionBackground(Color.GREEN);
               }else if("Female".equals(g)){
                   sp.radio_female.setSelected(true);
                   sp.radio_female.setForeground(Color.PINK);
                   tblStudentList.setSelectionBackground(Color.RED);
               }
               sp.txt_birthdate.setDate(rs.getDate("birthdate"));
               sp.txt_age.setText(rs.getString("age"));
               sp.txt_contact.setText(rs.getString("contact"));
               sp.txt_address.setText(rs.getString("address"));               
             
               byte [] image = rs.getBytes("picture");
               ImageIcon imgIcon = new ImageIcon (new ImageIcon(image).getImage().getScaledInstance(sp.label_photo.getWidth(), sp.label_photo.getHeight(), Image.SCALE_SMOOTH));
               sp.label_photo.setIcon(imgIcon);
               
               String ac = rs.getString("status");
               if("Active".equals(ac)){
                   sp.check_Active.setSelected(true);
                   sp.check_Active.setForeground(Color.green);
                   tblStudentList.setSelectionBackground(Color.GREEN);
                   
               }else if("Not Active".equals(ac)){
                   sp.check_NotActive.setSelected(true);
                   sp.check_NotActive.setForeground(Color.red);
                   tblStudentList.setSelectionBackground(Color.RED);
               }
               sp.setVisible(true);
               sp.toFront();
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
       
   
    
    }//GEN-LAST:event_tblStudentListMouseClicked

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        if(txt_search.getText().length() >= 30) {
            evt.consume();
        }
        String stringHolder = (String) cmb_filter.getSelectedItem();
        char c = evt.getKeyChar();
        switch (stringHolder) {
            case "Select":
                if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE || Character.isWhitespace(c))) {
                    evt.consume();
                }
                break;
            
            case "ID":
                if (!(Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
                    evt.consume();
                }
                break;    
                
            case "LastName":
                if (!(Character.isAlphabetic(c) || Character.isWhitespace(c))) {
                    evt.consume();
                }
                break;
            
            case "FirstName":
                if (!(Character.isAlphabetic(c) || Character.isWhitespace(c))) {
                    evt.consume();
                }
                break;
            
            case "MiddleName":
                if (!(Character.isAlphabetic(c) || Character.isWhitespace(c))) {
                    evt.consume();
                }
                break;    
        }
    }//GEN-LAST:event_txt_searchKeyTyped

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        
        try {
            if(cmb_filter.getSelectedItem().equals("ID")){
                String sql = "SELECT * FROM students WHERE ID LIKE '%"+txt_search.getText()+"%' ";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                tblStudentList.setModel(DbUtils.resultSetToTableModel(rs));
                showTableResize(); 
                
            }else if(cmb_filter.getSelectedItem().equals("LastName")){
                String sql = "SELECT * FROM students WHERE LastName LIKE '%"+txt_search.getText()+"%' ";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                tblStudentList.setModel(DbUtils.resultSetToTableModel(rs));
                showTableResize(); 
            
            }else if(cmb_filter.getSelectedItem().equals("FirstName")){
                String sql = "SELECT * FROM students WHERE FirstName LIKE '%"+txt_search.getText()+"%' ";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                tblStudentList.setModel(DbUtils.resultSetToTableModel(rs));
                showTableResize();
                
            }else if(cmb_filter.getSelectedItem().equals("MiddleName")){
                String sql = "SELECT * FROM students WHERE MiddleName LIKE '%"+txt_search.getText()+"%' ";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                tblStudentList.setModel(DbUtils.resultSetToTableModel(rs));
                showTableResize();
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int YesOrNo = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?","System Logout", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 1)
        {
            // if click no
        }
        if(YesOrNo == 0)
        {
            // if click yes
            this.setVisible(false);
            LoginForm l = new LoginForm();
            l.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblStudentListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblStudentListKeyPressed
       if(evt.getKeyCode()==com.sun.glass.events.KeyEvent.VK_ENTER){ 
             StudentProfile sp = new StudentProfile();
        try {
            int row = tblStudentList.getSelectedRow();
            String Table_click=(tblStudentList.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM students WHERE id='"+Table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();            
            if(rs.next()) {
               sp.txt_id.setText(rs.getString("id"));
               sp.txt_firstname.setText(rs.getString("firstname"));
               sp.txt_middlename.setText(rs.getString("middlename"));
               sp.txt_lastname.setText(rs.getString("lastname"));
               String g = rs.getString("gender");
               if("Male".equals(g)){
                   sp.radio_male.setSelected(true);
                   sp.radio_male.setForeground(Color.GREEN);
                   tblStudentList.setSelectionBackground(Color.GREEN);
               }else if("Female".equals(g)){
                   sp.radio_female.setSelected(true);
                   sp.radio_female.setForeground(Color.PINK);
                   tblStudentList.setSelectionBackground(Color.RED);
               }
               sp.txt_birthdate.setDate(rs.getDate("birthdate"));
               sp.txt_age.setText(rs.getString("age"));
               sp.txt_contact.setText(rs.getString("contact"));
               sp.txt_address.setText(rs.getString("address"));               
             
               byte [] image = rs.getBytes("picture");
               ImageIcon imgIcon = new ImageIcon (new ImageIcon(image).getImage().getScaledInstance(sp.label_photo.getWidth(), sp.label_photo.getHeight(), Image.SCALE_SMOOTH));
               sp.label_photo.setIcon(imgIcon);
               
               String ac = rs.getString("status");
               if("Active".equals(ac)){
                   sp.check_Active.setSelected(true);
                   sp.check_Active.setForeground(Color.green);
                   tblStudentList.setSelectionBackground(Color.GREEN);
                   
               }else if("Not Active".equals(ac)){
                   sp.check_NotActive.setSelected(true);
                   sp.check_NotActive.setForeground(Color.red);
                   tblStudentList.setSelectionBackground(Color.RED);
               }
               sp.setVisible(true);
               sp.toFront();
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
       }
    }//GEN-LAST:event_tblStudentListKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/                
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_filter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_entry;
    public javax.swing.JLabel label_user;
    public static javax.swing.JTable tblStudentList;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
